### ISSUE TITLE
Error: cannot open device with path IOService:/AppleACPIPlatformExpert

### ISSUE THREAD

**Issue by tomoyuki28jp** [hussy-io/truffle-ledger-provider#1] opened 2018-04-19 06:22 UTC
macOS High Sierra (10.13.4)
Ledger Nano S 1.4.2

`truffle migrate` raises following error:

```
tomo@Tomoyukis-MacBook-Pro ~/s/tmc> truffle migrate --reset --network ropsten_with_ledger
Using network 'ropsten_with_ledger'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x0c58e7cf61117a2ae570ef36db22f257e1098a5bdd6b0ff94d48e4818d1ae84
  Migrations: 0x8ac142006e48fdbcad8511713307a3d2c0176534
Saving successful migration to network...
  ... 0x9dd15bf4455870ef4b9648ddeb55423476f9f3b1fd2d8ba38ef3071b217d4c0
Saving artifacts...
Running migration: 2_deploy_contracts.js
Saving successful migration to network...
  Running step...
  Deploying TomoCoin...
(node:835) UnhandledPromiseRejectionWarning: Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS11@14600000/Nano S@14600000/Nano S@0/IOUSBHostHIDDevice@14600000,0
    at ProviderError.ExtendableError (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10:1)
    at new ProviderError (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/error.js:17:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:71:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:129:1
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/web3-provider-engine/index.js:129:9
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:473:16
    at replenish (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:983:17)
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:958:16
    at async.eachSeries.resultObj.id (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/web3-provider-engine/index.js:111:9)
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:998:17)
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:1002:9
    at eachLimit$1 (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:3182:24)
    at Object.<anonymous> (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/dist/async.js:1032:16)
    at end (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/web3-provider-engine/index.js:106:11)
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/internal/once.js:12:16
    at next (/Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/waterfall.js:21:29)
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/@ledgerhq/web3-subprovider/node_modules/web3-provider-engine/dist/es5/subproviders/hooked-wallet.js:413:21
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/@ledgerhq/web3-subprovider/node_modules/web3-provider-engine/dist/es5/subproviders/hooked-wallet.js:456:21
    at /Users/tomo/node_modules/truffle-ledger-provider/node_modules/@ledgerhq/web3-subprovider/src/index.js:181:23
    at <anonymous>
(node:835) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:835) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ... 0x1e97673e067dc9dae4083fd3b03891252a42e28cddd1e3b98d459c9f0e73215
Saving artifacts...
```

**Comment by petertulala** [comment] 2018-05-17 16:46
Not able to reproduce. Please provide a code, closing for now.

**Closed by petertulala** 2018-05-17 16:46 UTC
